### PR TITLE
Fixed several PHP 8.1 issues

### PR DESCRIPTION
**Pull request by Tjitse-E**
I cherry picked https://github.com/fooman/TCPDF/commit/342ca36ae722a0957a37354c49429d755584ca23 and https://github.com/fooman/TCPDF/commit/a9f01d6762133f98dc3b569ab04c7405cc830142 from the original TCPDF module and added https://github.com/fooman/TCPDF/commit/7448e6283f0db5f4f1e4cf62044473f840bf1645 (which was the issue I encountered in our Magento project).

### CODE REVIEW

**Comment by fooman** [comment]
hi @Tjitse-E thanks for sending through your changes. We'll run some tests with it on our end and push it as a new release.

Do you mind confirming how you triggered the error in your project?

**Comment by Tjitse-E** [comment]
Hi @fooman , that's hard to say, since it was over a month ago. From what I remember, I tried to open a PDF invoice (from Fooman PDF customizer), and it crashed after the PHP 8.1 update.

**Comment by fooman** [comment]
Ok the change makes sense to me was just hoping to be able to replicate it prior to merging as this is not something we have come across elsewhere. The code location would implicate that a certain image may not have a type.

**Comment by fooman** [comment]
Hey @Tjitse-E thanks again for providing those changes. I have included them in the latest release 6.5.0-p1 together with an upstream merge of their changes. Your changes, as is, would likely not make it into the upstream release as they are still keeping 5.3 compatiblity 😮 I'll keep an eye on this on future updates.

**Pull request merged**
